### PR TITLE
Clean up code removed sound utils

### PR DESCRIPTION
**Pull request by montlikadani**
Other:
- Smaller folder creation problem fix.

I think it works on other versions as well. (1.13)

### CODE REVIEW

**Comment by IdkMan2** [comment]
Great job man. I am sad because author of the plugin is inactive.

**Comment by brunyman** [comment]
Where did you put the sounds now? They need to be updated for 1.13 and i can't find them.

**Comment by montlikadani** [comment]
You will not find it because I removed it because it is unnecessary. If you need it, I'll make it into the configuration to write a boolean about whether to play audio when running this command.

**Comment by montlikadani** [comment]
Closed because you will not accept it.

**Pull request closed without merging**
